version: 1
disable_existing_loggers: false

formatters:
  standard:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
  
  detailed:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(filename)s:%(lineno)d - %(funcName)s - %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
  
  json:
    format: '{"timestamp": "%(asctime)s", "logger": "%(name)s", "level": "%(levelname)s", "message": "%(message)s", "module": "%(filename)s", "line": %(lineno)d}'
    datefmt: '%Y-%m-%d %H:%M:%S'

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: standard
    stream: ext://sys.stdout
  
  file_audiobroadcast:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: detailed
    filename: logs/audiobroadcast_bot.log
    maxBytes: 10485760  # 10MB
    backupCount: 5
    encoding: utf-8
  
  file_audioforwarder:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: detailed
    filename: logs/audioforwarder_bot.log
    maxBytes: 10485760  # 10MB
    backupCount: 5
    encoding: utf-8
  
  file_audioreceiver:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: detailed
    filename: logs/audioreceiver_bot.log
    maxBytes: 10485760  # 10MB
    backupCount: 5
    encoding: utf-8
  
  file_relay:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: detailed
    filename: logs/websocket_relay.log
    maxBytes: 10485760  # 10MB
    backupCount: 5
    encoding: utf-8
  
  file_startup:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: detailed
    filename: logs/bot_startup.log
    maxBytes: 10485760  # 10MB
    backupCount: 5
    encoding: utf-8

loggers:
  # Main application loggers
  audiobroadcast_bot:
    level: INFO
    handlers: [console, file_audiobroadcast]
    propagate: false
  
  audioforwarder_bot:
    level: INFO
    handlers: [console, file_audioforwarder]
    propagate: false
  
  audioreceiver_bot:
    level: INFO
    handlers: [console, file_audioreceiver]
    propagate: false
  
  websocket_relay:
    level: INFO
    handlers: [console, file_relay]
    propagate: false
  
  # Core component loggers
  bots.core:
    level: INFO
    handlers: [console, file_audiobroadcast]
    propagate: false
  
  bots.config:
    level: INFO
    handlers: [console, file_audiobroadcast]
    propagate: false
  
  bots.audio_handler:
    level: INFO
    handlers: [console, file_audiobroadcast]
    propagate: false
  
  # Third-party library loggers (suppress noisy ones)
  discord.voice_state:
    level: WARNING
    handlers: [file_audiobroadcast]
    propagate: false
  
  discord.gateway:
    level: WARNING
    handlers: [file_audiobroadcast]
    propagate: false
  
  discord.client:
    level: WARNING
    handlers: [file_audiobroadcast]
    propagate: false
  
  websockets:
    level: WARNING
    handlers: [file_audiobroadcast]
    propagate: false
  
  aiohttp.access:
    level: WARNING
    handlers: [file_audiobroadcast]
    propagate: false
  
  aiohttp.client:
    level: WARNING
    handlers: [file_audiobroadcast]
    propagate: false

root:
  level: INFO
  handlers: [console, file_startup]
