version: 1
disable_existing_loggers: false

formatters:
  # Development formatter - detailed with file/line info
  development:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(filename)s:%(lineno)d - %(funcName)s - %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
  
  # Production formatter - clean and minimal
  production:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
  
  # Standard formatter - balanced
  standard:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
  
  # JSON formatter for structured logging
  json:
    format: '{"timestamp": "%(asctime)s", "logger": "%(name)s", "level": "%(levelname)s", "message": "%(message)s", "module": "%(filename)s", "line": %(lineno)d}'
    datefmt: '%Y-%m-%d %H:%M:%S'

handlers:
  # Console handlers
  console_dev:
    class: logging.StreamHandler
    level: DEBUG
    formatter: development
    stream: ext://sys.stdout
  
  console_prod:
    class: logging.StreamHandler
    level: WARNING
    formatter: production
    stream: ext://sys.stdout
  
  console_standard:
    class: logging.StreamHandler
    level: INFO
    formatter: standard
    stream: ext://sys.stdout
  
  # File handlers for main bots
  file_audiobroadcast:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: development
    filename: logs/audiobroadcast_bot.log
    maxBytes: 10485760  # 10MB
    backupCount: 5
    encoding: utf-8
  
  file_audioforwarder:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: development
    filename: logs/audioforwarder_bot.log
    maxBytes: 10485760  # 10MB
    backupCount: 5
    encoding: utf-8
  
  file_audioreceiver:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: development
    filename: logs/audioreceiver_bot.log
    maxBytes: 10485760  # 10MB
    backupCount: 5
    encoding: utf-8
  
  file_relay:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: development
    filename: logs/websocket_relay.log
    maxBytes: 10485760  # 10MB
    backupCount: 5
    encoding: utf-8
  
  file_launcher:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: development
    filename: logs/launcher.log
    maxBytes: 10485760  # 10MB
    backupCount: 5
    encoding: utf-8
  
  # Production file handlers (WARNING and above)
  file_prod_audiobroadcast:
    class: logging.handlers.RotatingFileHandler
    level: WARNING
    formatter: production
    filename: logs/audiobroadcast_bot.log
    maxBytes: 10485760  # 10MB
    backupCount: 3
    encoding: utf-8
  
  file_prod_audioforwarder:
    class: logging.handlers.RotatingFileHandler
    level: WARNING
    formatter: production
    filename: logs/audioforwarder_bot.log
    maxBytes: 10485760  # 10MB
    backupCount: 3
    encoding: utf-8
  
  file_prod_audioreceiver:
    class: logging.handlers.RotatingFileHandler
    level: WARNING
    formatter: production
    filename: logs/audioreceiver_bot.log
    maxBytes: 10485760  # 10MB
    backupCount: 3
    encoding: utf-8
  
  file_prod_relay:
    class: logging.handlers.RotatingFileHandler
    level: WARNING
    formatter: production
    filename: logs/websocket_relay.log
    maxBytes: 10485760  # 10MB
    backupCount: 3
    encoding: utf-8
  
  file_prod_launcher:
    class: logging.handlers.RotatingFileHandler
    level: WARNING
    formatter: production
    filename: logs/launcher.log
    maxBytes: 10485760  # 10MB
    backupCount: 3
    encoding: utf-8

loggers:
  # Main application loggers - Development configuration
  audiobroadcast_bot:
    level: DEBUG
    handlers: [console_dev, file_audiobroadcast]
    propagate: false
  
  audioforwarder_bot:
    level: DEBUG
    handlers: [console_dev, file_audioforwarder]
    propagate: false
  
  audioreceiver_bot:
    level: DEBUG
    handlers: [console_dev, file_audioreceiver]
    propagate: false
  
  websocket_relay:
    level: DEBUG
    handlers: [console_dev, file_relay]
    propagate: false
  
  launcher:
    level: DEBUG
    handlers: [console_dev, file_launcher]
    propagate: false
  
  # Core component loggers
  bots.core:
    level: DEBUG
    handlers: [console_dev, file_audiobroadcast]
    propagate: false
  
  bots.config:
    level: DEBUG
    handlers: [console_dev, file_audiobroadcast]
    propagate: false
  
  bots.audio_handler:
    level: DEBUG
    handlers: [console_dev, file_audiobroadcast]
    propagate: false
  
  # Bot sub-component loggers
  forwarder_bot.events:
    level: DEBUG
    handlers: [console_dev, file_audioforwarder]
    propagate: false
  
  forwarder_bot.websocket:
    level: DEBUG
    handlers: [console_dev, file_audioforwarder]
    propagate: false
  
  forwarder_bot.performance:
    level: DEBUG
    handlers: [console_dev, file_audioforwarder]
    propagate: false
  
  receiver_bot.events:
    level: DEBUG
    handlers: [console_dev, file_audioreceiver]
    propagate: false
  
  receiver_bot.websocket:
    level: DEBUG
    handlers: [console_dev, file_audioreceiver]
    propagate: false
  
  receiver_bot.audio:
    level: DEBUG
    handlers: [console_dev, file_audioreceiver]
    propagate: false
  
  receiver_bot.performance:
    level: DEBUG
    handlers: [console_dev, file_audioreceiver]
    propagate: false
  
  # Infrastructure loggers
  infrastructure:
    level: DEBUG
    handlers: [console_dev, file_launcher]
    propagate: false
  
  networking:
    level: DEBUG
    handlers: [console_dev, file_relay]
    propagate: false
  
  subscription:
    level: DEBUG
    handlers: [console_dev, file_launcher]
    propagate: false
  
  # Module-specific loggers
  audio.handlers:
    level: DEBUG
    handlers: [console_dev, file_audiobroadcast]
    propagate: false
  
  audio.buffers:
    level: DEBUG
    handlers: [console_dev, file_audiobroadcast]
    propagate: false
  
  subscription.database:
    level: DEBUG
    handlers: [console_dev, file_launcher]
    propagate: false
  
  subscription.discord_api:
    level: DEBUG
    handlers: [console_dev, file_launcher]
    propagate: false
  
  subscription.manager:
    level: DEBUG
    handlers: [console_dev, file_launcher]
    propagate: false
  
  api.app:
    level: DEBUG
    handlers: [console_dev, file_launcher]
    propagate: false
  
  api.server:
    level: DEBUG
    handlers: [console_dev, file_launcher]
    propagate: false
  
  # Third-party library loggers (always suppress noisy ones)
  discord.voice_state:
    level: WARNING
    handlers: [file_audiobroadcast]
    propagate: false
  
  discord.gateway:
    level: WARNING
    handlers: [file_audiobroadcast]
    propagate: false
  
  discord.client:
    level: WARNING
    handlers: [file_audiobroadcast]
    propagate: false
  
  websockets:
    level: WARNING
    handlers: [file_audiobroadcast]
    propagate: false
  
  aiohttp.access:
    level: WARNING
    handlers: [file_audiobroadcast]
    propagate: false
  
  aiohttp.client:
    level: WARNING
    handlers: [file_audiobroadcast]
    propagate: false

root:
  level: DEBUG
  handlers: [console_dev, file_launcher]
